authguard:
  injection:
    packages: [ "com.authguard" ]

  jwt:
    algorithm: "HMAC256"
    privateKey: "FKvL11DI5rwgt51QgB3CVob3oWYrFNBzF0ROvu9Yaj8"
    issuer: "AuthGuard"
    allowedAlgorithms: ["HMAC256"]
    trustedIssuers: ["self"]

  exchange:
    allowed:
      - from: "basic"
        to: "otp"
      - from: "basic"
        to: "accessToken"
      - from: "refresh"
        to: "accessToken"
      - from: "otp"
        to: "accessToken"
      - from: "basic"
        to: "authorizationCode"
      - from: "authorizationCode"
        to: "accessToken"
      - from: "basic"
        to: "passwordless"
      - from: "passwordless"
        to: "accessToken"

  accessToken:
    tokenLife: "5m"
    refreshTokenLife: "1h"
    useJti: true
    includePermissions: true
    includeRoles: true

  otp:
    lifeTime: "2m"
    mode: "NUMERIC"
    length: 6
    generateToken: "accessToken"

  passwordless:
    tokenLife: "1h"
    randomSize: 128
    generateToken: "accessToken"

  authorizationCode:
    lifeTime: "5m"
    randomSize: 128

  authentication:
    generateToken: "authorizationCode"

  account:
    verifyEmail: true

  verification:
    verifyEmailUrlTemplate: "http://gateway/authguard/verify/email?token=${token}"
    emailVerificationLife: "1d"

  oneTimeAdmin:
    usernameVariable: "AUTHGUARD_OTA_USERNAME"
    passwordVariable: "AUTHGUARD_OTA_PASSWORD"

  emb:
    channels:
      - accounts
      - auth
